import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        cred: {
          black: "#000000",
          void: "#060608",
          surface: "#0c0c0e",
          "surface-elevated": "#141418",
          card: "#0e0e11",
          border: "rgba(255, 255, 255, 0.08)",
          "border-bright": "rgba(255, 255, 255, 0.2)",
          green: "#00E599",
          emerald: "#10B981",
          cyan: "#00F0FF",
          amber: "#FFA502",
          red: "#FF4757",
        },
        nexus: {
          bg: "#000000",
          surface: "#0c0c0e",
          "surface-secondary": "#141418",
          border: "rgba(255, 255, 255, 0.08)",
          "text-primary": "#FFFFFF",
          "text-secondary": "#9E9EA7",
          muted: "#666670",
          accent: "#FFFFFF",
          "accent-steel": "#8A8A93",
          positive: "#00E599",
          negative: "#FF4757",
          warning: "#FFA502",
        },
        intel: {
          dark: "#000000",
          card: "#0c0c0e",
          border: "rgba(255, 255, 255, 0.08)",
          cyan: "#00F0FF",
          emerald: "#00E599",
          amber: "#FFA502",
          rose: "#FF4757",
          purple: "#A855F7",
        },
      },
      fontFamily: {
        sans: [
          "Plus Jakarta Sans",
          "Outfit",
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
        display: [
          "Outfit",
          "Plus Jakarta Sans",
          "sans-serif",
        ],
        mono: [
          "JetBrains Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "monospace",
        ],
      },
      boxShadow: {
        'cred-card': 'inset 0 1px 0 0 rgba(255, 255, 255, 0.12), 0 20px 40px -15px rgba(0, 0, 0, 0.85)',
        'cred-pill': '0 0 30px rgba(255, 255, 255, 0.25)',
        'cred-glow-green': '0 0 25px rgba(0, 229, 153, 0.3)',
      },
    },
  },
  plugins: [],
};
export default config;
